#!/bin/bash
defaults read com.apple.finder CreateDesktop | grep 'true' &> /dev/null

if [ $? == 0 ];
then
	defaults write com.apple.finder CreateDesktop false
else
	defaults write com.apple.finder CreateDesktop true
fi

killAll Finder

